# -*- coding: utf-8 -*-
"""Copy of coop_sql_murder_mystery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DbWw97hiC-F5nx64F3YNBI0EWGYJWjIh

# SQL Murder Mystery!
Adapted By: Martin Arroyo

![Detective making connections between points](https://github.com/freestackinitiative/coop_sql_notebooks/blob/v2/assets/sleuth.png?raw=1)

**Credit**

This material was adapted from the [SQL Murder Mystery by Knight Lab](https://mystery.knightlab.com/) under [Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). The SQL Murder Mystery was originally created by [Joon Park](https://twitter.com/joonparkmusic) and [Cathy He](https://twitter.com/Cathy_MeiyingHe) while they were Knight Lab fellows. See the [GitHub repository](https://github.com/NUKnightLab/sql-mysteries) for more information.
"""



"""## Scenario

A crime has taken place and detectives need your help! You were given the crime scene report, but you somehow lost it. You vaguely remember that the crime was a `​murder`​ that occurred sometime on `​January 15, 2018`​ and that it took place in ​`SQL City`​. It is up to you to find out who the murderer is using just your SQL skills and resourcefulness. You are given a connection to the Police Department's database which has all of the clues you'll need to track down the killer.

Use the skills you developed in SQL 101 and 102, along with any resources you like, to solve the `SQL Murder Mystery`!

## Connect to the Police Department Database

To get started and run your queries, press play in the cell below to connect to the Police Department database.

To run queries, create a new `Code` cell and write `%%sql` at the top of it. Then you can write your queries underneath. See the example below:
```python
%%sql

SELECT *
FROM table

```
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture --no-stderr
# # @title Press Play { display-mode: "form" }
# # Install `teachdb` and `coop_grader`
# print("Installing `teachdb` and its dependencies...")
# %pip install --quiet --upgrade git+https://github.com/freestackinitiative/teachingdb.git git+https://github.com/martinmarroyo/coop_grader.git
# print("Successfully installed `teachdb`")
# from teachdb.teachdb import connect_teachdb
# from coop_grader.sql_murder_mystery.check_suspect import check_suspect
# # Set configurations for notebook & load data
# con = connect_teachdb(database="sql_murder_mystery")
# 
# %sql con

"""## Discovering tables in the database

We start our quest to find the murderer by exploring the Police Department database. But you haven't seen the database yet, and you don't know what the tables are, so how do you know what to look for?

Thankfully, most relational database management systems have this information stored in a place where you can query it. Very often, a special schema known as the [`information_schema`](https://en.wikipedia.org/wiki/Information_schema) is used to store information about the tables and columns in your database (aka metadata.) The police department's database has an information schema, with the `tables` view showing you what tables are available, and the `columns` view which shows you all the columns for each table and their data types.

### Listing all the tables in the Police Database

#### Check the [`information_schema.tables` description](https://duckdb.org/docs/sql/information_schema.html#tables-and-views)

First, we'll look at all the tables available to us by checking the `information_schema.tables` view. We'll give you the first query to start, but from here on out you will have to come up with the remaining queries using your SQL knowledge and your resourcefulness.

Here is the query that is needed to show you the tables in the Police Department Database. Copy/Paste it into the cell below and run it to see the tables available to you:

>```sql
>SELECT *
>FROM information_schema.tables
>```
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM information_schema.tables

"""### Listing all the tables and their columns in the Police Database

**Check the [`information_schema.columns` description](https://duckdb.org/docs/sql/information_schema.html#columns)**

Great! Now that you know what tables are available, it's time to find out the columns that each table has along with the data type of each column. Write a query that shows the table name, column name, and data type for each table in the Police Department database using the `information_schema.columns` view. Make sure that the output is ordered by table, then column name (ascending):

*Optional hints - try to only use them if you get **REALLY** stuck!*

<details>
<summary>Hint 1</summary>
<p>Structure your query just like we did in the previous one where we looked at `information_schema.tables`</p>
</details>

<details>
<summary>Hint 2</summary>
<p>Make sure to check the link for the information_schema.columns description! It will tell you the column names that you should use for the query. Remember, we want the table name, column name, and data type - check the description to find the appropriate names!</p>
</details>

<details>
<summary>Hint 3</summary>
<p>Don't forget to use the ORDER BY statement to order your search results. We are looking to sort both columns in ascending order, which can be specified using the ASC keyword, however, it is also the default sort order, so ASC is not necessarily required.</p>
</details>
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT table_name, column_name, data_type
# FROM information_schema.columns
# ORDER BY table_name, column_name ASC

"""### Entity Relationship Diagram (Optional)

After doing some detective work and finding the tables in the Police Department database, you discover that there is an ERD! This can be really helpful in your quest to find the murderer. If you like, challenge yourself (and your SQL skills) to continue on by just querying the `information_schema` as needed. Otherwise, you can click the dropdown below to reveal the ERD to help you see the tables and relationships in the Police Department database at a glance:

<details>
  <summary>Check the SQL Murder Mystery ERD</summary>
  <img src="https://github.com/freestackinitiative/coop_sql_notebooks/blob/v2/assets/murder_mystery_schema.png?raw=1" alt="ERD for SQL Murder Mystery"/>
</details>

## Beginning your investigation

Start by retrieving the corresponding crime scene report from the police department’s database.

<details>
<summary>Clue #1</summary>
<p>Look at the tables available in the Police Department database. Could the crime scene report be in there?</p>
</details>

<details>
<summary>Clue #2</summary>
<p>The murder occured on January 15, 2018 in SQL City. Perhaps filtering your query with this information can help you find that crime report you're looking for...</p>
</details>
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT date, description, city, type
# FROM crime_scene_report
# WHERE city ='SQL City' AND date = '20180115'
# 
# 
# 
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM interview
# WHERE person_id = '67318'
# 
# 
#

"""___

## Solving the Mystery (and checking if you cracked the case!)

From here on out, you'll be using your skills and the clues in the Police Department database to find the killer. When you think you have found the killer, come back to this section and use the cell below to check your answer and see if you found the murderer:

ex:
```python
check_suspect("Adam Levine")
```
"""

check_suspect("Miranda Priestly")

"""---

## Workspace

Use the cells below to write your queries and work on solving the mystery. When you have a suspect, check your answer using the [cell above this one](#solving-the-mystery-and-checking-if-you-cracked-the-case) and running their name through the `check_suspect` function. If you find the murderer, the function will tell you.

Don't forget to use `%%sql` at the top of the `Code` cells you create in order to get your SQL queries to work. Good luck, sleuths!
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM person
# WHERE license_id = '291182'
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM person
# WHERE name LIKE 'A%' AND address_street_name = 'Franklin Ave'

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM person
# WHERE address_street_name = 'Northwestern Dr'
# ORDER BY address_number DESC

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM interview
# WHERE person_id = '16371'

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM interview
# WHERE person_id = '14887'

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM get_fit_now_check_in
# WHERE check_in_date = '20180109' AND membership_id LIKE '48Z%'

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM get_fit_now_member
# WHERE id = '48Z7A'

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM get_fit_now_member
# WHERE id = '48Z55'